[project]
name = "etl-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8.10"
dependencies = [
    "numpy>=1.24.4",
    "pandas>=2.0.3",
    "pyodbc>=5.2.0",
]
